// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDetJU2AljQZ7s_HgqCCUeMrG8YqKiR6AM',
    appId: '1:615839265732:web:1eed9ef4fb053aa2df6a91',
    messagingSenderId: '615839265732',
    projectId: 'cities-world',
    authDomain: 'cities-world.firebaseapp.com',
    storageBucket: 'cities-world.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSDrtX-ZY116ovWewxk9uxMMOLtbsVm6k',
    appId: '1:615839265732:android:3f83030549113c9edf6a91',
    messagingSenderId: '615839265732',
    projectId: 'cities-world',
    storageBucket: 'cities-world.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9IzfOaQwwptbXeRLztzgQDR4FFUbHqg0',
    appId: '1:615839265732:ios:0bbc6dfc1d483e49df6a91',
    messagingSenderId: '615839265732',
    projectId: 'cities-world',
    storageBucket: 'cities-world.appspot.com',
    iosClientId: '615839265732-bu0ivqqt9q7lonflj6d7ttfcr5ev7cm6.apps.googleusercontent.com',
    iosBundleId: 'com.example.smashFrontendCitiesworld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9IzfOaQwwptbXeRLztzgQDR4FFUbHqg0',
    appId: '1:615839265732:ios:0bbc6dfc1d483e49df6a91',
    messagingSenderId: '615839265732',
    projectId: 'cities-world',
    storageBucket: 'cities-world.appspot.com',
    iosClientId: '615839265732-bu0ivqqt9q7lonflj6d7ttfcr5ev7cm6.apps.googleusercontent.com',
    iosBundleId: 'com.example.smashFrontendCitiesworld',
  );
}
